#pragma once
enum CardsInOldDeck
{
	0 == Masked_Beast_Des_Gardius,
	1 == Melchid_The_Four_Face_Beast,
	2 == Chaos_Necromancer,
	3 == Spirit_Reaper,
	4 == Ancient_Lamp,
	5 == Grand_Tiki_Elder,
	6 == Kuriboh,
	7 == Heavy_Storm,
	8 == The_Mask_Of_Remnants,
	9 == Possessed_Dark_Soul,
	10 == Dark_Necrofear,
	11 == Nobleman_Of_Crossout,
	12 == Newdoria,
	13 == Call_Of_The_Haunted,
	14 == Dark_Jeriod,
	15 == Archfiend_Soldier,
	16 == Mystic_Tomato,
	17 == Mystical_Space_Typhoon,
	18 == Newdoria,
	19 == Sakuretsu_Armor,
	20 == Sakuretsu_Armor,
	21 == Mystic_Tomato,
	22 == Brain_Control,
	23 == Giant_Orc,
	24 == Giant_Orc,
	25 == Enemy_Controller,
	26 == La_Jinn_The_Mystical_Genie_Of_The_Lamp,
	27 == Sangan,
	28 == Megamorph,
	29 == Mirror_Force,
	30 == Shrink,
	31 == Torrential_Tribute,
	32 == Premature_Burial,
	33 == Deck_Devastation_Virus,
	34 == Axe_Of_Despair,
	35 == Return_From_The_Different_Dimension,
	36 == Draining_Shield,
	37 == Slate_Warrior,
	38 == Nightmares_Steelcage,
	39 == Lightning_Vortex,
	40 == Monster_Reincarnation,
	41 == Jinzo,
	42 == Dark_Ruler_Ha_Des
};